# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: restore pip download cache
      uses: syphar/restore-pip-download-cache@v1
    - name: autopy-lot 
      uses: deep5050/autopy-lot@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        check: all # latest
        input_type: py
        comment_magics: true
        split_at_heading: true
        output_type: ipynb
        output_dir: './jupyter/'
    - name: Automatic requirements.txt for Python Projects
      uses: ryan-rozario/pipreqs-action@v2.0.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
